version: "3.7"

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 
      MYSQL_ROOT_PASSWORD: enterprise2022@


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  app:
    build: .
    container_name: ignite-entregas
    ports:
      - 3000:3000
    volumes:
      - .:/user/app
